### ISSUE TITLE
FASMIFRA

### ISSUE THREAD

**Issue by UnixJunkie** [dengjianyuan/Survey_AI_Drug_Discovery#1]
Under: "Task*: Molecule Generation; Representation*: SMILES Strings"

Maybe you might be interested by this one:

Molecular generation by Fast Assembly of (Deep)SMILES fragments
https://jcheminf.biomedcentral.com/articles/10.1186/s13321-021-00566-4

https://github.com/UnixJunkie/FASMIFRA

Regards,
Francois.

**Comment by dengjianyuan** [comment]
Hi Francois, thanks for the great suggestion! I'll add your paper and repo to the list. =)
